// <auto-generated />
using System;
using BookStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Annotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PublishingHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BooksTb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5069f22c-0e69-4f03-b79d-c3244226c0fa"),
                            Annotation = "Труды Иосифа Флавия являются ценнейшим источником сведений по библейской, греческой и римской истории.",
                            Author = "Иосиф Флавий",
                            Cover = "/Images/Covers/IFJW.jpg",
                            CoverType = "мягкий",
                            Format = "18x12",
                            Genre = "История",
                            ISBN = "978-5-389-18167-0",
                            NumberOfPages = 640,
                            Price = 27m,
                            PublishingHouse = "Азбука",
                            Title = "Иудейская война",
                            Weight = 311,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("4f994aeb-224b-4651-8cef-2cd37ec02aea"),
                            Annotation = "Книга Книг ХХ века. Самое популярное, самое читаемое, самое культовое произведение ушедшего столетия.",
                            Author = "Джон Рональд Руэл Толкин",
                            Cover = "/Images/Covers/JRRTLOTR.jpg",
                            CoverType = "твёрдый",
                            Format = "22x14,5",
                            Genre = "Фантастика. Фэнтези",
                            ISBN = "978-5-17-094268-8",
                            NumberOfPages = 1120,
                            Price = 33m,
                            PublishingHouse = "АСТ",
                            Title = "Властелин Колец (трилогия)",
                            Weight = 1200,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("b9e0e0f4-d1f4-43e9-a9f9-755acf8ca93d"),
                            Annotation = "«Ветер в ивах» – детская повесть, которую с равным удовольствием читают дети и взрослые.",
                            Author = "Кеннет Грэм",
                            Cover = "/Images/Covers/KGWW.jpg",
                            CoverType = "твёрдый",
                            Format = "70x90",
                            Genre = "Классическая литература",
                            ISBN = "978-5-88350-002-1",
                            NumberOfPages = 208,
                            Price = 40m,
                            PublishingHouse = "Век",
                            Title = "Ветер в ивах",
                            Weight = 530,
                            Year = 1992
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
